name: Test CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: tests
    name: Test changed-files
    outputs:
      approved: ${{ steps.checking-files.outputs.approved }} 
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
      - name: List all changed files
        id: checking-files
        run: |
          if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -q "TEST.md"; then
            echo "{approved}={true}" >> $GITHUB_OUTPUT
            echo "1"
          else
            echo "{approved}={false}" >> $GITHUB_OUTPUT
            echo "2"
          fi  

  go_ahead:
    needs: build_and_push_docker
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Step1
        if: needs.build_and_push_docker.outputs.approved == 'true'
        run: |
          echo "Performing conditional action because TEST.md was changed."
      - name: Conditional Step2
        if: needs.build_and_push_docker.outputs.approved == 'false'
        run: |
          echo "Do nothing"     
