name: Test CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build_and_push_docker:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check if TEST.md is Updated
        run: |
          for commit in "${{ github.event.commits }}"; do
            if git diff-tree --no-commit-id --name-only -r "$commit" | grep -q "TEST.md"; then
              exit 1
              break
            fi
          done
      # - name: Print Pull Request Event
      #   run: echo "${{ toJson(github.event.pull_request) }}"
  go_ahead:
    needs: build_and_push_docker
    runs-on: ubuntu-latest
    steps:
      - name: helloworld
        run: |
          echo "helloworld"
