name: Test CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build_and_push_docker:
    needs: tests
    runs-on: ubuntu-latest
    # if: github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'TEST.md')
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
      # - name: Print Pull Request Event
      #   run: echo "${{ toJson(github.event.pull_request) }}"
